COMMON:
  DEVICE: "cuda:1"       
  SEED: 34
  NUM_CLASSES: 2
  IMG_SIZE: 224
  PATCH_SIZE: 16

  # Full / Partial
  MEAN: [0.48177003860473633, 0.2620476186275482, 0.0985482931137085] 
  STD: [0.23788580298423767, 0.13709917664527893, 0.05762823671102524]
  
  # # Scalable
  # MEAN: [0.49139249324798584, 0.259649395942688, 0.10012753307819366]
  # STD: [0.24435177445411682, 0.13781645894050598, 0.06025311350822449]

  WEIGHT_DECAY: 1e-3
  LEARNING_RATE: 0.003
  MOMENTUM: 0.9
  LOCAL_EPOCH: 1
  BATCH_SIZE: 32
  TRAIN_RATIO: 0.75
  ADAPFT: True
  MODEL_PATH: '/workspace/fed-mdmae/results/full/global_model.pt'
  PARTIAL_LABEL_RATIO: 0.8
  PARTIAL_SEED: 42

SERVER:
  GLOBAL_ROUNDS: 500
  NUM_CLIENTS: 5
  JOIN_RATIO: 1             # 매 라운드 참여 비율
  ALGORITHM: "fedavg"
  GOAL: ""
  CLIENT_DROP_RATE: 0      # 네트워크 오류 시 클라이언트 제외 확률
  TIME_THRESHOLD: 100000       # 클라이언트 응답 시간 제한 (초)
  EVAL_GAP: 10             # 평가 주기 (라운드 단위)

CLIENTS:
  NMC:
    NAME: "NMCDataset"
    IMAGE_PATH: "/data/fundus_dataset/NMC/cropped_images/"
    CSV_PATH: "/data/fundus_dataset/NMC/final_label.csv"

  APTOS:
    NAME: "APTOSDataset"
    IMAGE_PATH: "/data/fundus_dataset/APTOS/cropped_images/"
    CSV_PATH: "/data/fundus_dataset/APTOS/final_label.csv"

  ODIR:
    NAME: "ODIRDataset"
    IMAGE_PATH: "/data/fundus_dataset/ODIR-5K/ODIR-5K/cropped_images/"
    CSV_PATH: "/data/fundus_dataset/ODIR-5K/ODIR-5K/final_label.csv"

  IDRiD:
    NAME: "IDRiDDataset"
    IMAGE_PATH: "/data/fundus_dataset/IDRiD/cropped_images/"
    CSV_PATH: "/data/fundus_dataset/IDRiD/final_label.csv"

  MESSIDOR:
    NAME: "MESSIDORDataset"
    IMAGE_PATH: "/data/fundus_dataset/MESSIDOR/cropped_images/"
    CSV_PATH: "/data/fundus_dataset/MESSIDOR/final_label.csv"
