COMMON:
  DEVICE: "cuda:0"       
  SEED: 34
  NUM_CLASSES: 1
  MODEL: "MaskedAutoencoderViT"
  IMAGE_SIZE: 224
  PATCH_SIZE: 16
  HYBRID: False
  BASE_LR: 1e-4
  WARMUP_EPOCHS: 5
  MEAN: [0.48177003860473633, 0.2620476186275482, 0.0985482931137085]
  STD: [0.23788580298423767, 0.13709917664527893, 0.05762823671102524]

SERVER:
  GLOBAL_ROUNDS: 1000
  NUM_CLIENTS: 5
  JOIN_RATIO: 1             # 매 라운드 참여 비율
  ALGORITHM: "FedAvg"
  GOAL: "FedAvg-LPE"
  CLIENT_DROP_RATE: 0      # 네트워크 오류 시 클라이언트 제외 확률
  TIME_THRESHOLD: 100000       # 클라이언트 응답 시간 제한 (초)
  EVAL_GAP: 10                 # 평가 주기 (라운드 단위)
  USE_FEDBN: False

CLIENTS:
  NMC:
    NAME: "NMCDataset"
    IMAGE_PATH: "/data/fundus_dataset/NMC/cropped_images/"
    CSV_PATH: "/data/fundus_dataset/NMC/final_label.csv"
    LOCAL_EPOCH: 1
    BATCH_SIZE: 32
    LEARNING_RATE: 1e-4
    MASK_RATIO: 0.6
    TRAIN_RATIO: 0.75
    BETAS: [0.9, 0.95]
    WEIGHT_DECAY: 0.05
    EPS: 1e-8
    ACCUM_ITER: 1

  APTOS:
    NAME: "APTOSDataset"
    IMAGE_PATH: "/data/fundus_dataset/APTOS/cropped_images/"
    CSV_PATH: "/data/fundus_dataset/APTOS/final_label.csv"
    LOCAL_EPOCH: 1
    BATCH_SIZE: 32
    LEARNING_RATE: 1e-4
    MASK_RATIO: 0.6
    TRAIN_RATIO: 0.75
    BETAS: [0.9, 0.95]
    WEIGHT_DECAY: 0.05
    EPS: 1e-8
    ACCUM_ITER: 1

  ODIR:
    NAME: "ODIRDataset"
    IMAGE_PATH: "/data/fundus_dataset/ODIR-5K/ODIR-5K/cropped_images/"
    CSV_PATH: "/data/fundus_dataset/ODIR-5K/ODIR-5K/final_label.csv"
    LOCAL_EPOCH: 1
    BATCH_SIZE: 32
    LEARNING_RATE: 1e-4
    MASK_RATIO: 0.6
    TRAIN_RATIO: 0.75
    BETAS: [0.9, 0.95]
    WEIGHT_DECAY: 0.05
    EPS: 1e-8
    ACCUM_ITER: 1

  IDRiD:
    NAME: "IDRiDDataset"
    IMAGE_PATH: "/data/fundus_dataset/IDRiD/cropped_images/"
    CSV_PATH: "/data/fundus_dataset/IDRiD/final_label.csv"
    LOCAL_EPOCH: 1
    BATCH_SIZE: 32
    LEARNING_RATE: 1e-4
    MASK_RATIO: 0.6
    TRAIN_RATIO: 0.75
    BETAS: [0.9, 0.95]
    WEIGHT_DECAY: 0.05
    EPS: 1e-8
    ACCUM_ITER: 1

  MESSIDOR:
    NAME: "MESSIDORDataset"
    IMAGE_PATH: "/data/fundus_dataset/MESSIDOR/cropped_images/"
    CSV_PATH: "/data/fundus_dataset/MESSIDOR/final_label.csv"
    LOCAL_EPOCH: 1
    BATCH_SIZE: 32
    LEARNING_RATE: 1e-4
    MASK_RATIO: 0.6
    TRAIN_RATIO: 0.75
    BETAS: [0.9, 0.95]
    WEIGHT_DECAY: 0.05
    EPS: 1e-8
    ACCUM_ITER: 1
