NAME: 'MESSIDOR'
DATASET: 'MESSIDORDataset'

SEED: 34
IMG_SIZE: 224
PATCH_SIZE: 16
EPOCHS: 100
BATCH_SIZE: 16
TRAIN_RATIO: 0.75
ENCODER_LR: 1e-4
CLASSIFIER_LR: 1e-4
WEIGHT_DECAY: 1e-4 
NUM_CLASSES: 2  
IMG_DIR: "/data/fundus_dataset/MESSIDOR/cropped_images/"
CSV_DIR: "/data/fundus_dataset/MESSIDOR/final_label.csv"
DEVICE: 'cuda:1'

GOAL: 'qa_fedproto'


# # Scratch
# MEAN: [0.518355131149292, 0.24622619152069092, 0.08210893720388412]
# STD: [0.2827285826206207, 0.13944843411445618, 0.05185171589255333]
# SAVE_PATH: '/workspace/fed-mdmae/results/scratch/'
# SCRATCH: True
# HYBRID: False
# FREEZE: False
# ADAPFT: False

# Fine-tuning
MEAN: [0.48177003860473633, 0.2620476186275482, 0.0985482931137085]  
STD: [0.23788580298423767, 0.13709917664527893, 0.05762823671102524]

# FedAvg-LPE
MODEL_PATH: '/workspace/fed-mdmae/results/partial/global_model.pt'
BN_PATH: 
SAVE_PATH: '/workspace/fed-mdmae/results/'
SCRATCH: False
HYBRID: False
#
FREEZE: True
ADAPFT: True

# # FedAvg-CPE
# MODEL_PATH: '/workspace/fed-mdmae/results/fedavg_cpe/pretraining/global_model.pt'
# BN_PATH: 
# SAVE_PATH: '/workspace/fed-mdmae/results/fedavg_cpe/finetuning/'
# SCRATCH: False
# HYBRID: True
# #
# FREEZE: True
# ADAPFT: False

# # FedBN-CPE
# MODEL_PATH: '/workspace/fed-mdmae/results/fedbn_cpe/pretraining/global_model.pt'
# BN_PATH: '/workspace/fed-mdmae/results/fedbn_cpe/pretraining/client_MESSIDOR_bn.pt'
# SAVE_PATH: '/workspace/fed-mdmae/results/fedbn_cpe/finetuning/'
# SCRATCH: False
# HYBRID: True
# #
# FREEZE: True
# ADAPFT: False
