NAME: 'NMC'
DATASET: 'NMCDataset'

SEED: 34
IMG_SIZE: 224
PATCH_SIZE: 16
EPOCHS: 100
BATCH_SIZE: 64
TRAIN_RATIO: 0.75
ENCODER_LR: 1e-4
CLASSIFIER_LR: 1e-4
WEIGHT_DECAY: 1e-4 
NUM_CLASSES: 2  
IMG_DIR: '/data/fundus_dataset/NMC/cropped_images/'
CSV_DIR: '/data/fundus_dataset/NMC/final_label.csv'
DEVICE: 'cuda:1'

GOAL: 'qa_fedproto'

# # Scratch
# MEAN: [0.4432830810546875, 0.27163752913475037, 0.09224271774291992] 
# STD: [0.21202681958675385, 0.13422399759292603, 0.04710434749722481]
# SAVE_PATH: '/workspace/fed-mdmae/results/scratch/'
# SCRATCH: True
# HYBRID: False
# FREEZE: False
# ADAPFT: False

# Fine-tuning
MEAN: [0.48177003860473633, 0.2620476186275482, 0.0985482931137085]  
STD: [0.23788580298423767, 0.13709917664527893, 0.05762823671102524]

# FedAvg-LPE
MODEL_PATH: '/workspace/fed-mdmae/results/partial/global_model.pt'
BN_PATH: 
SAVE_PATH: '/workspace/fed-mdmae/results/'
SCRATCH: False
HYBRID: False
#
FREEZE: True
ADAPFT: True

# # FedAvg-CPE
# MODEL_PATH: '/workspace/fed-mdmae/results/fedavg_cpe/pretraining/global_model.pt'
# BN_PATH: 
# SAVE_PATH: '/workspace/fed-mdmae/results/fedavg_cpe/finetuning/'
# SCRATCH: False
# HYBRID: True
# #
# FREEZE: True
# ADAPFT: False

# # FedBN-CPE
# MODEL_PATH: '/workspace/fed-mdmae/results/fedbn_cpe/pretraining/global_model.pt'
# BN_PATH: '/workspace/fed-mdmae/results/fedbn_cpe/pretraining/client_NMC_bn.pt'
# SAVE_PATH: '/workspace/fed-mdmae/results/fedbn_cpe/finetuning/'
# SCRATCH: False
# HYBRID: True
# #
# FREEZE: True
# ADAPFT: False

