NAME: 'ODIR'
DATASET: 'ODIRDataset'

SEED: 34
IMG_SIZE: 224
PATCH_SIZE: 16
EPOCHS: 100
BATCH_SIZE: 32
TRAIN_RATIO: 0.75
ENCODER_LR: 1e-4
CLASSIFIER_LR: 1e-4
WEIGHT_DECAY: 1e-4 
NUM_CLASSES: 2  
IMG_DIR: "/data/fundus_dataset/ODIR-5K/ODIR-5K/cropped_images/"
CSV_DIR: "/data/fundus_dataset/ODIR-5K/ODIR-5K/final_label.csv"
DEVICE: 'cuda:1'

GOAL: 'qa_fedproto'

# # Scratch
# MEAN: [0.442617267370224, 0.2822388708591461, 0.15392082929611206]
# STD: [0.2514511048793793, 0.16845344007015228, 0.09767929464578629]
# SAVE_PATH: '/workspace/fed-mdmae/results/scratch/'
# SCRATCH: True
# HYBRID: False
# FREEZE: False
# ADAPFT: False

# Fine-tuning
MEAN: [0.48177003860473633, 0.2620476186275482, 0.0985482931137085]  
STD: [0.23788580298423767, 0.13709917664527893, 0.05762823671102524]

# FedAvg-LPE
MODEL_PATH: '/workspace/fed-mdmae/results/partial/global_model.pt'
BN_PATH: 
SAVE_PATH: '/workspace/fed-mdmae/results/'
SCRATCH: False
HYBRID: False
#
FREEZE: True
ADAPFT: True

# # FedAvg-CPE
# MODEL_PATH: '/workspace/fed-mdmae/results/fedavg_cpe/pretraining/global_model.pt'
# BN_PATH: 
# SAVE_PATH: '/workspace/fed-mdmae/results/fedavg_cpe/finetuning/'
# SCRATCH: False
# HYBRID: True
# #
# FREEZE: True
# ADAPFT: False

# # FedBN-CPE
# MODEL_PATH: '/workspace/fed-mdmae/results/fedbn_cpe/pretraining/global_model.pt'
# BN_PATH: '/workspace/fed-mdmae/results/fedbn_cpe/pretraining/client_ODIR_bn.pt'
# SAVE_PATH: '/workspace/fed-mdmae/results/fedbn_cpe/finetuning/'
# SCRATCH: False
# HYBRID: True
# #
# FREEZE: True
# ADAPFT: False
